model: module.mamba.MambaDetector
ssl:
  name: wav2vec2
  ckpt: facebook/wav2vec2-xls-r-300m
  out_type: hidden_state
  hidden_size: 1024
  pool_head: 1
  finetune_mode: default
classifier:
  enable_moe: False
  hidden_size: 512
  n_layers: 3
optim:
  learning_rate: 0.0001
  weight_decay: 0.0001
scheduler:
  step_size: 10
  gamma: 0.5
objective:
  loss1:
    name: frame
    type: mask_ce
    weight: 1.0
  loss2:
    name: boundary
    type: balance
    args:
      negative_ratio: 5
    weight: 0.5
  # loss3:
  #   name: reg
  #   type: direct
  #   weight: 0.1