model: module.model.PartialDetector
ssl:
  name: wav2vec2
  ckpt: facebook/wav2vec2-xls-r-300m
  out_type: hidden_state
  hidden_size: 1024
  # [Fix]: freeze the wav2vec2 parameters; 
  # [lora]: use LoRA to finetune Transformer blocks; 
  # [default]: finetune Transformer blocks
  finetune_mode: lora
  lora_rank: 16
  lora_alpha: 32
  lora_target_modules: ["q_proj", "v_proj"]
classifier:
  proj_size: 512
  hidden_size: 512
  n_layers: 3
  pool: attention
return_emb: h2 # h1: for SSL features directly, h2: for features before pooling, h3: for features after pooling
optim:
  learning_rate: 0.0001
  weight_decay: 0.0001
scheduler:
  step_size: 10
  gamma: 0.5
objective:
  loss1:
    name: frame
    type: mask_ce
    weight: 1.0
  loss2:
    name: boundary
    type: balance
    args:
      negative_ratio: 5
    weight: 0.1
  loss3:
    name: tcl
    type: tcl
    args:
      pos_margin: 0.8
      neg_margin: 0.2
      smooth_weight: 1.0
      boundary_weight: 2.0
    weight: 0.5
  