samplerate: 16000
resolution: 0.02
input_maxlength: ~
input_minlength: 3200  # 0.2 second / 10 unit frames
label_maxlength: 200
segment_split_ratio: 1.8  # longer than label_maxlength * segment_split_ratio will be split


datasets:
  eval_set:
    - name: had-test
      label_root: data/HAD/HAD_test_seglab_0.02.npy
      data_root: data/HAD/HAD_test/test
      dur_lst: ~
      filters:
        0: HAD
        1: test
      augment: False
    
augmentors: ~