samplerate: 16000
resolution: 0.02
input_maxlength: ~
input_minlength: 3200  # 0.2 second / 10 unit frames
label_maxlength: 200
segment_split_ratio: 1.8  # longer than label_maxlength * segment_split_ratio will be split


datasets:
  eval_set:
    - name: partialedit-CaP
      label_root: data/PartialEdit/PartialEdit_E1E2_seglab_0.02.npy
      data_root: data/PartialEdit/wav
      dur_lst: ~
      filters:
        0: CAP
        1: E1,E2
      augment: False
    - name: partialedit-Edi
      label_root: data/PartialEdit/PartialEdit_E1E2_seglab_0.02.npy
      data_root: data/PartialEdit/wav
      dur_lst: ~
      filters:
        0: EDI
        1: E1,E2
      augment: False
    
augmentors: ~