samplerate: 16000
resolution: 0.16
input_maxlength: ~
input_minlength: ~
label_maxlength: 25
segment_split_ratio: 1.8  # longer than label_maxlength * segment_split_ratio will be split

datasets:
  train_set:
    - name: PES-train-cap
      label_root: data/PES/annotations/train_seglab_0.02.npy
      data_root: data/PES/train
      dur_lst: data/PES_train_duration.lst
      filters:
        0: CAP,REF  # CAP,EDI,FUL,REF
        1: FLT,SAT,SSR,NAN  # FLT,SAT,SSR,NAN
      augment: True # !IMPORTANT to enable augment for training set
  dev_set:
    - name: PES-dev-cap
      label_root: data/PES/annotations/dev_seglab_0.02.npy
      data_root: data/PES/dev
      dur_lst: data/PES_dev_duration.lst
      filters:
        0: CAP,REF
        1: FLT,SAT,SSR,NAN
      augment: False
  eval_set:
    - name: PES-eval-ful
      label_root: data/PES/annotations/eval_seglab_0.02.npy
      data_root: data/PES/eval
      dur_lst: data/PES_eval_duration.lst
      filters:
        0: FUL,REF
        1: FLT,SAT,SSR,NAN
      augment: False
    - name: PES-eval-cap
      label_root: data/PES/annotations/eval_seglab_0.02.npy
      data_root: data/PES/eval
      dur_lst: data/PES_eval_duration.lst
      filters:
        0: CAP,REF
        1: FLT,SAT,SSR,NAN
      augment: False
    - name: PES-eval-edi
      label_root: data/PES/annotations/eval_seglab_0.02.npy
      data_root: data/PES/eval
      dur_lst: data/PES_eval_duration.lst
      filters:
        0: EDI,REF
        1: FLT,SAT,SSR,NAN
      augment: False

augmentors:
  - name: waveglow
    p: 0.8
    cache_key: wglow